name : Deploy to VPS

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPSHOST }}
          username: ${{ secrets.VPSUSER }}
          key: ${{ secrets.VPSSSHKEY }}
          script: |
            cd app
            docker build -t vchallenge .
            docker stop vchallenge || true
            docker rm vchallenge || true
            docker run -d --name vchallenge --restart=always vchallenge